const screens = {
  LANDING_SCREEN: 'LandingScreen',
  AUTH_SCREEN: 'AuthScreen',
  VERIFICATION_SCREEN: 'VerificationScreen',
  HOME: 'Home',
  HOME_STACK: 'HomeStack',
  JOBS: 'Jobs',
  MESSAGES: 'Messages',
  FAVOURITES: 'Favourites',
  FOLDERS_STACK: 'FolderStack',
  FOLDER_DETAIL: 'FolderDetail',
  POST_JOB: 'Post job',
  REVIEW_DETAILS: 'Review Details',
  CREATE_PROFILE: 'Create Profile',
  EDITOR_HOME_STACK: 'EditorHomeStack',
  EDITOR_HOME: 'Editor Home',
  PROPOSALS: 'Proposals',
  SHARE_VIDEO: 'Share Video',
  EDITOR_PROFILE: 'Profile',
  VIDEO: 'Video',
};
export default screens;
