const strings = {
  welcome: 'Welcome to OpenEdit',
  get_started: 'Get started by Choosing your \n' + 'account type',
  i_am_client: 'I am a Client',
  i_am_editor: 'I am an Editor',
  already_member: 'Already a member? Sign in',
  create_new_account: 'Create a new account',
  get_great_experience: 'Get great experience with tracky',
  signup: 'Sign Up',
  signin: 'Sign In',
  full_name: 'Full Name',
  enter_your_name: 'Enter your name',
  phone_number: 'Phone Number',
  enter_your_number: 'Enter your number',
  password: 'Password',
  enter_your_password: 'Enter your password',
  create_account: 'Create Account',
  or_signup_with: 'Or Sign Up With',
  verification_code: 'Verification Code',
  we_sent_verification_code:
    'We have sent the code verification to\n' + 'your number',
  submit: 'Submit',
  did_nt_receive_code: 'Didn’t receive the code? ',
  resend: 'Resend',
  login_to_continue: 'Log in to continue',
  or_signin_with: 'Or Sign In With',
};
export default strings;
